Site features Pull Request
GloireIrenge/ReviewChecker pull request #1
Opened 2022-07-06 21:08 UTC by GloireIrenge

2022-07-06 21:39 UTC, GloireIrenge commented on css/index.css
> +body{
Use two spaces instead of tabulation to ensure you respect the CSS best practice

2022-07-06 21:42 UTC, GloireIrenge commented on index.html
>          <input type="checkbox">
### Be careful with blank lines and indentation.

1. Do not add blank lines, spaces, or indentations without a reason.
2. For readability, add blank lines to separate large or logical code blocks.
3. For readability, add two spaces of indentation. Do not use the tab key.
4. on some code editors, you can set the tab button to do an X amount of spaces.

2022-07-06 21:49 UTC, GloireIrenge reviewed
Hi @GloireIrenge ,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
### Highlights
-  Your codes are working
-  Some commits are described

### Required Changes
Please kindly check the comments below for more details.

**Remember to:**

- Use Linter.
- Document your repository in a professional way.
- Respect the CSS and HTML best practice

Cheers and Happy coding!

2022-07-06 22:10 UTC, mirouhml requested changes
# REQUIRED CHANGES 🔴

Hi @GloireIrenge, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media4.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif?cid=ecf05e47n6s5huda7qh40syoppcaspe9vx68ddmxerd08owm&rid=giphy.gif&ct=g)

## Highlights

- Great job setting up the correct linters ✔️
- Highly organized and clean code ✔️ 👨🏻‍💻
- Professional documentation ✔️
- Correct workflow ✔️
- Meaningful commit messages ✔️

## Required Changes ♻️
_Check the comments under the review._

- [ ] You should be more polite by using `kindly` and `please` rather than using orders 😉, for example, you said:

- Do not add blank lines, spaces, or indentations without a reason.

But it should be like this:

- Kindly don't add blank lines, spaces, or indentations without a reason.

Kindly change your comment to reflect what I said. 😁

---

- [ ] Also you should give a reason of why you're requesting a change, for example instead of saying:

- Why don't you use an article tag here instead of a div?

You should say:

- Why don't you use an article tag for the .first-article element instead of a div, that would improve the HTML structure and make the page more accessible.

Please change your comment to reflect what I said. 😁


## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

- [ ] Consider using emojis and gifs in your review please, as it makes it look more human-friendly.
- [ ] Please know that you should use the "Start review" feature when reviewing rather than putting single comments each time, to explain, you start by highlighting the piece of code you want to write a comment about then you get this screen: 😁
![image](https://user-images.githubusercontent.com/20567503/177651202-729df7a8-86cf-4acf-af43-41a7c4115e00.png)
As you can see you have the option to start reviewing and posting a single comment, you should start reviewing as it makes your comments pending and not posted they'll only be posted after you click on this button and put your summary: 😁
![image](https://user-images.githubusercontent.com/20567503/177651301-731a853e-a680-4461-814f-d8dbfe852108.png)

---

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-07 05:34 UTC, muneebulrehman approved these changes
Hi @GloireIrenge , 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🥳
Congratulations! 🎉 

# Status: Approved✔️
- Good follow-up with the previous reviewer.

## Highlights

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-07 05:48 UTC, merged